### PR TITLE
Provide better examples for MCRouter

### PR DESCRIPTION
**Pull request by sgolemon**
The existing example was just a repurposed unit test which isn't
as meaningful as a piece of documentation.

### CODE REVIEW

**Comment by fredemmott** [comment]
Please split this out to another file - if it's in a separate file, we can automatically test it (at least with the typechecker). Inline examples, we can't.

**Comment by JoelMarcey** [comment]
@sgolemon Sorry about that. I forgot to mention that we are doing examples a bit differently. Basically, we put examples in their own PHP file.

So you will just want to change the example here:

https://github.com/hhvm/hack-hhvm-docs/blob/master/__docs/phpdoc/sample-code/hack.mcrouter1.php

and then https://github.com/hhvm/hack-hhvm-docs/blob/master/__docs/phpdoc/en/hackref/mcrouter/examples.xml will just map it automatically.

**Comment by sgolemon** [comment]
Yeah, I noticed you were putting them elsewhere, I was just hoping to buck that. :p

I quite like having the examples with their output, but I didn't think of the typechecker.  I'll move these over.

**Comment by JoelMarcey** [comment]
I had planned to move the output into their own files too -- basically modify our test runner to be workable for these examples too.

**Pull request merged**
